### ISSUE TITLE
Click hyperlinks from HTML

### ISSUE THREAD

**Issue by WillBishop** [instacart/Nantes#19]
**Is your feature request related to a problem? Please describe.**
I'd love it if hyperlinks from HTML could be clicked. At the moment I construct an NSMutableAttributedString from an HTML string (built-in functionality to iOS), which colors my links but I can not click them.

**Describe the solution you'd like**
An option to initialize NantesLabel with an HTML string so that it can parse the HTML and display clickable hyperlinks

**Describe alternatives you've considered**
Trying to calculate the range of links but I thought that'd be too difficult.

Example String: "\<a href=\"http://www.google.com">I can't be clicked</a>"

**Comment by spadafiva** [comment]
@WillBishop I'm pretty sure that your use case will be fixed by #18, and is the same issue as #15 .  If you want to test it out you could try pulling from my fork in #18

**Comment by spadafiva** [comment]
I added a test case for what you're describing to my pr: https://github.com/instacart/Nantes/pull/18/commits/79a5ad310ab94e70a65a75d8222f810b98d5de98

**Comment by chansen22** [comment]
@WillBishop this should be working in `master` now

**Comment by chansen22** [comment]
@WillBishop going to close this. Feel free to update if you run into anything!
