### ISSUE TITLE
Example build failure

### ISSUE THREAD

**Issue by coderzhuo** [instacart/Nantes#31]
**Describe the bug**
I follow your instructions and run the project after executing the pod install command in the Example directory. The result is wrong.

**Screenshots**
![屏幕快照 2019-05-21 上午10 45 36](https://user-images.githubusercontent.com/31040713/58064686-b061b080-7bb5-11e9-80fa-1a7f6013bf95.png)

**Operating environment**
Xcode Version: 10.2.1
Device:  Simulator iPhone 8plus

**Comment by chansen22** [comment]
#34 will fix this. As a workaround, use version 0.0.7 instead of the master branch in your podfile

**Comment by chansen22** [comment]
Hey @coderzhuo this should be fixed now. Feel free to try out `0.0.8`.
