### ISSUE TITLE
It seems that Nantes doesn't support NSAttributedString.Key.strikethroughStyle. Any plans yet?

### ISSUE THREAD

**Issue by Semty** [instacart/Nantes#36]
It seems that Nantes doesn't support NSAttributedString.Key.strikethroughStyle. Any plans yet?

**Comment by chansen22** [comment]
Currently it uses its own key for strikeouts. You can checkout `NSAttributedString.Key.nantesLabelStrikeOut` for now if you want, but I'll see what I can do about adding support for `NSAttributedString.Key.strikethroughStyle`.

There's an example in the example repo if you want to try the Nantes specific one [here](https://github.com/instacart/Nantes/blob/master/Example/Nantes/ViewController.swift#L147).

**Comment by Semty** [comment]
> Currently it uses its own key for strikeouts. You can checkout `NSAttributedString.Key.nantesLabelStrikeOut` for now if you want, but I'll see what I can do about adding support for `NSAttributedString.Key.strikethroughStyle`.
> 
> There's an example in the example repo if you want to try the Nantes specific one [here](https://github.com/instacart/Nantes/blob/master/Example/Nantes/ViewController.swift#L147).

Thanks for the great answer, NSAttributedString.Key.nantesLabelStrikeOut should be enough
