### ISSUE TITLE
Version 0.0.8 not available for cocoapods

### ISSUE THREAD

**Issue by PatrickDotStar** [instacart/Nantes#37]
The recent release of 0.0.8 is not available for install with cocoapods yet.

**Comment by namolnad** [comment]
Thanks for the heads up @PatrickDotStar. @chansen22 and I are working through this right now. 

We have some ownership issues with the pod as it was registered to his Instacart work email which is no longer valid. We'll keep you posted on our progress on this one — thanks again for the reminder and for your patience as we deal with this!

**Comment by namolnad** [comment]
@PatrickDotStar, we've sorted out the issues and have published the new version to CocoaPods. If you have any further issue with this, please reopen. Thanks!
