### ISSUE TITLE
Crash when emoji inside the text

### ISSUE THREAD

**Issue by samratpramanik** [instacart/Nantes#39]
**Describe the bug**
If a string contains emoji then crash unexpectedly at Truncation.swift file line of code: 

let originalLine = lines[originalIndex] 

Please fix this issue as soon as possible.

**Comment by samratpramanik** [comment]
![Screen Shot 2019-07-11 at 4 23 02 PM](https://user-images.githubusercontent.com/52668808/61048171-baa66b00-a3fe-11e9-83dc-8f2e6b702d07.png)

**Comment by samratpramanik** [comment]
![Screen Shot 2019-07-11 at 4 23 08 PM](https://user-images.githubusercontent.com/52668808/61048241-ee819080-a3fe-11e9-9842-e10e93e6dd93.png)

**Comment by samratpramanik** [comment]
![Screen Shot 2019-07-11 at 5 48 59 PM](https://user-images.githubusercontent.com/52668808/61050251-322ac900-a404-11e9-87f5-50cf78b3e8da.png)

**Comment by chansen22** [comment]
@samratpramanik would you mind posting your code? I'm having a hard time reproducing this on my end. 

If possible, could you post the whole string you're using here and any setup code you do on the label before drawing it?

**Comment by chansen22** [comment]
@samratpramanik is this still crashing for you if you use the master branch?

**Comment by ngocholo** [comment]
@sandeepgs1984 v0.0.9 has been released. https://github.com/instacart/Nantes/releases/tag/0.0.9
This should fix issue. Closing.

**Comment by sandeepgs1984** [comment]
@chansen22 Thanks!!
