### ISSUE TITLE
Version 0.0.9 not available for cocoapods

### ISSUE THREAD

**Issue by sandeepgs1984** [instacart/Nantes#43]
Hi, 

Please support the newer release 0.0.9 for cocoapods. Please find the below logs:

[!] CocoaPods could not find compatible versions for pod "Nantes":
  In Podfile:
    Nantes (= 0.0.9)

None of your spec sources contain a spec satisfying the dependency: `Nantes (= 0.0.9)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by goergisn** [comment]
Any update on this? Currently we're specifying a specific commit in our podfile

**Comment by ngocholo** [comment]
Thanks for reporting. Bumping version here https://github.com/instacart/Nantes/pull/48

**Comment by ngocholo** [comment]
We're sorting out issues with updating the Cocoapods Specs repo. Will update as soon as it's resolved.

**Comment by ngocholo** [comment]
Should be ready. You may need to run `pod repo update`.

Will close issue. Feel free to reopen if issue still persists.

**Comment by sandeepgs1984** [comment]
It's fine now.. Thanks!!
