### ISSUE TITLE
Bug managing taps and events

### ISSUE THREAD

**Issue by Ricardo1980** [instacart/Nantes#45]
Hello,

In the sample app, if you add a tap gesture recognizer to the view controller view, then the label does not detect touches anymore.

Try adding this in the viewDidLoad
```
        let gr = UITapGestureRecognizer(target: self, action: #selector(onTest))
        view.addGestureRecognizer(gr)
```

and this method:
```
    @objc func onTest(sender: UITapGestureRecognizer) {
        print("--onTest")
    }
```

Now try to click for example "terms and conditions" or "privacy policy".

The label does not work when we touch a link and the gesture recognizer method is executed. The strange thing is that if you maintain the tap and move it far from the label and release it, sometimes it works properly, calling the label method and not the gesture recognizer we created.
I guess there is a problem in the logic regarding UIResponder. Any suggestions? Thanks.

The expected behaviour is that the nantes label consumes the event completely and the view behind it does not receive the tap event.

I am using version 0.0.8 and iOS 12 and 13.

**Comment by ngocholo** [comment]
@Ricardo1980 That's the default behavior with gesture recognizers where they may block touches from propagating to the view it's added to or its subviews. I believe you can set `cancelsTouchesInView` to `false` to achieve the behavior you want.

**Comment by ngocholo** [comment]
Issue likely not related to Nantes. Closing. Feel free to reopen if that's not the case.
