### ISSUE TITLE
Setting an attributedText value containing link as String

### ISSUE THREAD

**Issue by AlexZd** [instacart/Nantes#49]
Hello,
you did a fix related to this #15 issue and it is working fine only when attributed string contains URL as link. And as confirmation you can see this code:
```Swift
extension NSAttributedString {
    func findExistingLinks() -> Set<NSTextCheckingResult> {
        var relinks: Set<NSTextCheckingResult> = []
        enumerateAttribute(.link,
                           in: NSRange(location: 0, length: length),
                           options: []) { attribute, linkRange, _ in
                            if let url = attribute as? URL {
                                relinks.insert(NSTextCheckingResult.linkCheckingResult(range: linkRange, url: url))
                            }
        }
        return relinks
    }
}
```
Why you didn't allow `String` ?
So it would be more easier if handle this scenario also:
```Swift
if let linkString = attribute as? String, let url = URL(string: linkString) {
```

The reason - from some parsing libraries it is coming as `String` not as `URL`

**Comment by ngocholo** [comment]
@AlexZd  Sounds like a nice addition. Would you mind submitting a PR for it?

**Comment by AlexZd** [comment]
Sure, will do

**Comment by ngocholo** [comment]
Closing as this has been fixed with https://github.com/instacart/Nantes/pull/50.
