### ISSUE TITLE
Calculate boundingRect get wrong height 

### ISSUE THREAD

**Issue by CivelXu** [instacart/Nantes#6]
1. set attributedText to NantesLabel, include font, linespace;
2. Get height by func boundingRect, could not get right height
3. When  I replace  NantesLabel to UILabel, can get the right height

**Comment by chansen22** [comment]
Hi CivelXu, would you mind adding a unit test to the project that describes this for me? It'll help me get it fixed way faster that way. :)

**Comment by CivelXu** [comment]
OK， I will create a demo for you in my free time；
Now，I want to know how to get accurate height by given string content；

**Comment by chansen22** [comment]
Hmm. I think I found the issue. If you want, for now, you can work around the problem by setting up the label and then setting the `text` property on it after changing `lineSpacing` and `font`. Here's a quick example of what I'm talking about:

```
        let label: NantesLabel = .init(frame: .zero)
        label.numberOfLines = 0
        label.lineSpacing = 40
        label.font = .systemFont(ofSize: 14.0)
        label.text = ExampleString.linespace.rawValue
```

I'll try and get a fix worked up soon.

**Comment by chansen22** [comment]
https://github.com/instacart/Nantes/commit/4b540bc4503e8c7776ae0ec94cf1f2a3139736fe Should fix this for attributedStrings, but if you're just using `text` you'll have to do it in the order I listed in my earlier comment. Feel free to comment if you're having more problems with this!

**Comment by CivelXu** [comment]
Hi, To improve the project, I create a demo to show this issues;
I hope you come to review it sometime;
[NantesTest](https://github.com/CivelXu/NantesTest)
