### ISSUE TITLE
SPM error on 0.1.0

### ISSUE THREAD

**Issue by Kaspik** [instacart/Nantes#60]
**Describe the bug**
Nantes can't be used via SPM.

**To Reproduce**
Try to add Nantes via SPM

**Expected behavior**

**Screenshots**
<img width="673" alt="Screenshot 2020-06-22 at 11 46 26" src="https://user-images.githubusercontent.com/7204168/85273583-10441e00-b47e-11ea-9647-5721054fdc79.png">

**Additional context**
This problem was already described in the PR - https://github.com/instacart/Nantes/pull/54
Seems like it was added then but to the wrong place in Package.swift - correct one is not `target` - https://developer.apple.com/documentation/swift_packages/package

**Comment by ngocholo** [comment]
Thanks for the report. This has been fixed in version `0.1.1` https://github.com/instacart/Nantes/releases/tag/0.1.1
