### ISSUE TITLE
Xcode 12 warning about iOS simulator deployment target.

### ISSUE THREAD

**Issue by Prince2k3** [instacart/Nantes#64]
Xcode 12 release is showing this warning
```
The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.
```

**Comment by ruchiupgade-mb** [comment]
Still showing the same error - The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.

**Comment by MoNTE48** [comment]
@ngocholo, can you take a look at this?

**Comment by ngocholo** [comment]
@Prince2k3 @ruchiupgade-mb @MoNTE48 Could you provide what specific version of Xcode 12 you're seeing this issue on? And please include a sample project replicating this issue if you can.

**Comment by ngocholo** [comment]
Seems like it's an issue with installing using Cocoapods. There's a workaround for this by modifying your own Podfile to bump the deployment target of the pod(s). More details here https://github.com/CocoaPods/CocoaPods/issues/7314#issuecomment-355905199

**Comment by MoNTE48** [comment]
@ngocholo I use SWIFT Package...
Xcode... From 12.0 beta to 12.2 RC

**Comment by ruchiupgade-mb** [comment]
I use SPM and Xcode 12.0

**Comment by ngocholo** [comment]
I see. This has been fixed in the main branch. Will release a new version soon.

**Comment by ngocholo** [comment]
@MoNTE48 @ruchiupgade-mb @Prince2k3  version `0.1.2` has been released. This should fix the issues you're seeing.

Closing this issue. Feel free to drop a line if you're still seeing the warning.
